version: '3'
services:
  db:
    image: postgres:11
    environment:
      POSTGRES_DB: dashboard
      POSTGRES_USER: dashboard
      POSTGRES_PASSWORD: dashboard
  broker:
    image: redis
  frontend:
    build: .
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: '1'
      FIELD_ENCRYPTION_KEY: '1'
      DJANGO_DATABASE: production
      DB_ENGINE: postgresql_psycopg2
      DB_HOST: db
      BROKER: redis://broker:6379/0
  migrate:
    build: .
    image: internetstandards/dashboard
    restart: on-failure
    environment:
      SECRET_KEY: '1'
      FIELD_ENCRYPTION_KEY: '1'
      DJANGO_DATABASE: production
      DB_ENGINE: postgresql_psycopg2
      DB_HOST: db
    command: migrate
